---
title: "Class 17: Analyzing sequencing data in the cloud"
author: "Leah Kim A16973745"
format: pdf
toc: true
---

## Setup

```{r}
library(tximport)

# setup the folder and filenames to read
folders <- dir(pattern="SRR21568*")
samples <- sub("_quant", "", folders)
files <- file.path( folders, "abundance.h5" )
names(files) <- samples

txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)
```

```{r}
head(txi.kallisto$counts)
```

Number of transcripts for each sample:
```{r}
colSums(txi.kallisto$counts)
```

How many transcripts detected in at least one sample:
```{r}
sum(rowSums(txi.kallisto$counts)>0)
```

Filter out transcripts with no reads:
```{r}
to.keep <- rowSums(txi.kallisto$counts) > 0
kset.nonzero <- txi.kallisto$counts[to.keep,]
```

Filter out transcripts with no change:
```{r}
keep2 <- apply(kset.nonzero,1,sd)>0
x <- kset.nonzero[keep2,]
```

## PCA

Run PCA
```{r}
pca <- prcomp(t(x), scale=TRUE)
summary(pca)
```

### Plot of Transcriptomic Profiles

PC1 vs PC2:
```{r}
plot(pca$x[,1], pca$x[,2],
     col=c("blue","blue","red","red"),
     xlab="PC1", ylab="PC2", pch=16)
```

PC1 vs PC3:
```{r}
plot(pca$x[,1], pca$x[,3],
     col=c("blue","blue","green","green"),
     xlab="PC1", ylab="PC3", pch=16)
```

PC2 vs PC3:
```{r}
plot(pca$x[,2], pca$x[,3],
     col=c("red","red","green","green"),
     xlab="PC2", ylab="PC3", pch=16)
```